-- Auto-generated by export_wow_addon.py — do not edit.
local V = {}

V.has_data = true
V.run_id = "validate-20260824T012402.324484Z"
V.checked_at = "2026-08-24T01:42:51.357310+00:00"
V.checked_label = "2026-08-24 01:42"
V.status = "validated"
V.confirmed_at = "2026-08-24T01:42:51.357310+00:00"
V.confirmed_label = "2026-08-24 01:42"
V.is_full_run = true
V.is_current = false
V.overall = {
  upgrade_picks_pct = 97.5,
  upgrade_size_error_pct = 0.24,
  dps_read_error_pct = 0.25,
  scored_pairs = 237,
  spec_count = 35,
}
V.by_spec = {
  ["MID2_Death_Knight_Blood"] = {
    upgrade_picks_pct = 85.7,
    upgrade_size_error_pct = 0.268,
    dps_read_error_pct = 0.27,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Death_Knight_Blood_Deathbringer"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.086,
    dps_read_error_pct = 0.21,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Death_Knight_Frost"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.484,
    dps_read_error_pct = 6.41,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Death_Knight_Frost_Rider"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.373,
    dps_read_error_pct = 5.66,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Death_Knight_Unholy"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 1.513,
    dps_read_error_pct = 0.59,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Death_Knight_Unholy_San'layn"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.895,
    dps_read_error_pct = 0.25,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Demon_Hunter_Vengeance"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.173,
    dps_read_error_pct = 0.1,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Hunter_Beast_Mastery"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.083,
    dps_read_error_pct = 0.26,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Hunter_Marksmanship"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.819,
    dps_read_error_pct = 3.02,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Hunter_Survival"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.662,
    dps_read_error_pct = 1.41,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Mage_Arcane"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.149,
    dps_read_error_pct = 0.2,
    n_scored_pairs = 5,
    n_tie_pairs = 3,
  },
  ["MID2_Mage_Arcane_Sunfury"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.123,
    dps_read_error_pct = 0.09,
    n_scored_pairs = 4,
    n_tie_pairs = 4,
  },
  ["MID2_Mage_Fire"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.132,
    dps_read_error_pct = 0.14,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Mage_Fire_Frostfire"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.114,
    dps_read_error_pct = 0.07,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Mage_Frost"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.443,
    dps_read_error_pct = 0.13,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Mage_Frost_Frostfire"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.417,
    dps_read_error_pct = 0.33,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Monk_Brewmaster"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.113,
    dps_read_error_pct = 0.07,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Paladin_Protection"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.069,
    dps_read_error_pct = 0.26,
    n_scored_pairs = 5,
    n_tie_pairs = 3,
  },
  ["MID2_Paladin_Protection_Lightsmith"] = {
    upgrade_picks_pct = 85.7,
    upgrade_size_error_pct = 0.184,
    dps_read_error_pct = 0.19,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Priest_Shadow"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.249,
    dps_read_error_pct = 0.47,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Priest_Shadow_Archon"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.517,
    dps_read_error_pct = 0.21,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Rogue_Assassination"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.214,
    dps_read_error_pct = 0.14,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Rogue_Assassination_Fatebound"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.262,
    dps_read_error_pct = 0.13,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Rogue_Outlaw"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.288,
    dps_read_error_pct = 0.52,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Rogue_Subtlety"] = {
    upgrade_picks_pct = 85.7,
    upgrade_size_error_pct = 0.451,
    dps_read_error_pct = 0.08,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Shaman_Elemental"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.188,
    dps_read_error_pct = 0.08,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Shaman_Elemental_Stormbringer"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.166,
    dps_read_error_pct = 0.09,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Shaman_Enhancement"] = {
    upgrade_picks_pct = 71.4,
    upgrade_size_error_pct = 1.599,
    dps_read_error_pct = 2.36,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Shaman_Enhancement_Totemic"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.536,
    dps_read_error_pct = 3.28,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Warlock_Affliction"] = {
    upgrade_picks_pct = 85.7,
    upgrade_size_error_pct = 0.137,
    dps_read_error_pct = 0.28,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Warlock_Affliction_Hellcaller"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.071,
    dps_read_error_pct = 0.44,
    n_scored_pairs = 5,
    n_tie_pairs = 3,
  },
  ["MID2_Warlock_Demonology"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.24,
    dps_read_error_pct = 0.05,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Warlock_Destruction"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.235,
    dps_read_error_pct = 0.42,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Warlock_Destruction_Diabolist"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.555,
    dps_read_error_pct = 0.09,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Warrior_Protection"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.183,
    dps_read_error_pct = 0.52,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
}

_G.MrMythicalValidationExport = V
