-- Auto-generated by export_wow_addon.py — do not edit.
local V = {}

V.has_data = true
V.run_id = "validate-20260827T171249.028241Z"
V.checked_at = "2026-08-27T17:32:50.022301+00:00"
V.checked_label = "2026-08-27 17:32"
V.status = "validated"
V.confirmed_at = "2026-08-27T17:32:50.022301+00:00"
V.confirmed_label = "2026-08-27 17:32"
V.is_full_run = true
V.is_current = false
V.overall = {
  upgrade_picks_pct = 97.9,
  upgrade_size_error_pct = 0.251,
  dps_read_error_pct = 0.32,
  scored_pairs = 239,
  spec_count = 35,
}
V.by_spec = {
  ["MID2_Death_Knight_Blood"] = {
    upgrade_picks_pct = 85.7,
    upgrade_size_error_pct = 0.199,
    dps_read_error_pct = 0.23,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Death_Knight_Blood_Deathbringer"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.136,
    dps_read_error_pct = 0.31,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Death_Knight_Frost"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.549,
    dps_read_error_pct = 6.68,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Death_Knight_Frost_Rider"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.314,
    dps_read_error_pct = 6.36,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Death_Knight_Unholy"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 1.568,
    dps_read_error_pct = 0.96,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Death_Knight_Unholy_San'layn"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.862,
    dps_read_error_pct = 0.7,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Demon_Hunter_Vengeance"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.099,
    dps_read_error_pct = 0.12,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Hunter_Beast_Mastery"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.174,
    dps_read_error_pct = 0.26,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Hunter_Marksmanship"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.811,
    dps_read_error_pct = 3.11,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Hunter_Survival"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.642,
    dps_read_error_pct = 4.98,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Mage_Arcane"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.126,
    dps_read_error_pct = 0.14,
    n_scored_pairs = 5,
    n_tie_pairs = 3,
  },
  ["MID2_Mage_Arcane_Sunfury"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.137,
    dps_read_error_pct = 0.04,
    n_scored_pairs = 4,
    n_tie_pairs = 4,
  },
  ["MID2_Mage_Fire"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.179,
    dps_read_error_pct = 0.11,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Mage_Fire_Frostfire"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.214,
    dps_read_error_pct = 0.13,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Mage_Frost"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.529,
    dps_read_error_pct = 0.12,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Mage_Frost_Frostfire"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.41,
    dps_read_error_pct = 0.15,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Monk_Brewmaster"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.165,
    dps_read_error_pct = 2.35,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Paladin_Protection"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.116,
    dps_read_error_pct = 0.24,
    n_scored_pairs = 5,
    n_tie_pairs = 3,
  },
  ["MID2_Paladin_Protection_Lightsmith"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.093,
    dps_read_error_pct = 0.63,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Priest_Shadow"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.166,
    dps_read_error_pct = 0.43,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Priest_Shadow_Archon"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.616,
    dps_read_error_pct = 0.25,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Rogue_Assassination"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.189,
    dps_read_error_pct = 0.1,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Rogue_Assassination_Fatebound"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.315,
    dps_read_error_pct = 0.25,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Rogue_Outlaw"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.34,
    dps_read_error_pct = 0.32,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Rogue_Subtlety"] = {
    upgrade_picks_pct = 85.7,
    upgrade_size_error_pct = 0.345,
    dps_read_error_pct = 0.15,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Shaman_Elemental"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.116,
    dps_read_error_pct = 0.18,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Shaman_Elemental_Stormbringer"] = {
    upgrade_picks_pct = 87.5,
    upgrade_size_error_pct = 0.172,
    dps_read_error_pct = 0.19,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Shaman_Enhancement"] = {
    upgrade_picks_pct = 71.4,
    upgrade_size_error_pct = 1.527,
    dps_read_error_pct = 2.53,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Shaman_Enhancement_Totemic"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.528,
    dps_read_error_pct = 3.44,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Warlock_Affliction"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.769,
    dps_read_error_pct = 8.95,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Warlock_Affliction_Hellcaller"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.185,
    dps_read_error_pct = 13.74,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Warlock_Demonology"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.318,
    dps_read_error_pct = 10.23,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Warlock_Destruction"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.217,
    dps_read_error_pct = 2.1,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Warlock_Destruction_Diabolist"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.403,
    dps_read_error_pct = 2.11,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Warrior_Protection"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.251,
    dps_read_error_pct = 0.52,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
}

_G.MrMythicalValidationExport = V
