-- Auto-generated by export_wow_addon.py — do not edit.
local V = {}

V.has_data = true
V.run_id = "validate-20260821T193306.820897Z"
V.checked_at = "2026-08-21T19:48:51.669850+00:00"
V.checked_label = "2026-08-21 19:48"
V.status = "validated"
V.confirmed_at = "2026-08-21T19:48:51.669850+00:00"
V.confirmed_label = "2026-08-21 19:48"
V.is_full_run = true
V.is_current = false
V.overall = {
  upgrade_picks_pct = 94.8,
  upgrade_size_error_pct = 0.197,
  dps_read_error_pct = 0.94,
  scored_pairs = 194,
  spec_count = 29,
}
V.by_spec = {
  ["MID2_Death_Knight_Blood"] = {
    upgrade_picks_pct = 85.7,
    upgrade_size_error_pct = 0.142,
    dps_read_error_pct = 1.8,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Death_Knight_Blood_Deathbringer"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.139,
    dps_read_error_pct = 0.38,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Death_Knight_Frost"] = {
    upgrade_picks_pct = 87.5,
    upgrade_size_error_pct = 0.345,
    dps_read_error_pct = 1.23,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Death_Knight_Frost_Rider"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.227,
    dps_read_error_pct = 0.39,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Death_Knight_Unholy"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.495,
    dps_read_error_pct = 2.6,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Death_Knight_Unholy_San'layn"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.921,
    dps_read_error_pct = 0.04,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Demon_Hunter_Vengeance"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.301,
    dps_read_error_pct = 1.49,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Hunter_Beast_Mastery"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.164,
    dps_read_error_pct = 0.87,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Hunter_Marksmanship"] = {
    upgrade_picks_pct = 85.7,
    upgrade_size_error_pct = 0.248,
    dps_read_error_pct = 0.1,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Hunter_Survival"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.092,
    dps_read_error_pct = 0.98,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Mage_Arcane"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.109,
    dps_read_error_pct = 1.17,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Mage_Arcane_Sunfury"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.103,
    dps_read_error_pct = 1.27,
    n_scored_pairs = 4,
    n_tie_pairs = 4,
  },
  ["MID2_Mage_Fire"] = {
    upgrade_picks_pct = 85.7,
    upgrade_size_error_pct = 0.168,
    dps_read_error_pct = 0.06,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Mage_Fire_Frostfire"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.122,
    dps_read_error_pct = 1.23,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Mage_Frost"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.168,
    dps_read_error_pct = 0.15,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Mage_Frost_Frostfire"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.281,
    dps_read_error_pct = 0.67,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Paladin_Protection"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.1,
    dps_read_error_pct = 0.31,
    n_scored_pairs = 5,
    n_tie_pairs = 3,
  },
  ["MID2_Paladin_Protection_Lightsmith"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.222,
    dps_read_error_pct = 0.23,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Priest_Shadow"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.524,
    dps_read_error_pct = 0.97,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Priest_Shadow_Archon"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.568,
    dps_read_error_pct = 1.02,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Rogue_Subtlety"] = {
    upgrade_picks_pct = 85.7,
    upgrade_size_error_pct = 0.219,
    dps_read_error_pct = 0.98,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Shaman_Elemental"] = {
    upgrade_picks_pct = 83.3,
    upgrade_size_error_pct = 0.102,
    dps_read_error_pct = 0.21,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Shaman_Elemental_Stormbringer"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.118,
    dps_read_error_pct = 1.38,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Shaman_Enhancement"] = {
    upgrade_picks_pct = 75,
    upgrade_size_error_pct = 1.278,
    dps_read_error_pct = 0.94,
    n_scored_pairs = 8,
    n_tie_pairs = 0,
  },
  ["MID2_Shaman_Enhancement_Totemic"] = {
    upgrade_picks_pct = 75,
    upgrade_size_error_pct = 0.442,
    dps_read_error_pct = 1.16,
    n_scored_pairs = 4,
    n_tie_pairs = 4,
  },
  ["MID2_Warlock_Affliction"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.077,
    dps_read_error_pct = 0.77,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Warlock_Affliction_Hellcaller"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.197,
    dps_read_error_pct = 0.61,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
  ["MID2_Warlock_Destruction"] = {
    upgrade_picks_pct = 85.7,
    upgrade_size_error_pct = 0.132,
    dps_read_error_pct = 3.26,
    n_scored_pairs = 7,
    n_tie_pairs = 1,
  },
  ["MID2_Warlock_Destruction_Diabolist"] = {
    upgrade_picks_pct = 100,
    upgrade_size_error_pct = 0.271,
    dps_read_error_pct = 0.74,
    n_scored_pairs = 6,
    n_tie_pairs = 2,
  },
}

_G.MrMythicalValidationExport = V
